name: Build

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: CI tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Install codecov
        run: npm install codecov
      - name: Lint
        run: npm run lint
      - name: tests
        run: npm run test
